export const MOVIES_LIST_REQUEST = 'MOVIES_LIST_REQUEST'
export const MOVIES_LIST_SUCCESS = 'MOVIES_LIST_SUCCESS'
export const MOVIES_LIST_FAILURE = 'MOVIES_LIST_FAILURE'
export const MOVIES_LIST_RESET = 'MOVIES_LIST_RESET'

export const MOVIES_DETAIL_REQUEST = 'MOVIES_DETAIL_REQUEST'
export const MOVIES_DETAIL_SUCCESS = 'MOVIES_DETAIL_SUCCESS'
export const MOVIES_DETAIL_FAILURE = 'MOVIES_DETAIL_FAILURE'